export const BALANCE = {
  tacticalMap: {
    // The ground mesh spans -80..80. Keep the mothership inside this
    // smaller playable square so the outer six units can act as a visual
    // transition ring instead of exposing the floor's hard edge.
    groundHalfExtent: 80,
    playableHalfExtent: 74,
  },
  mothership: {
    maxHull: 1200,
    maxShield: 800,
    maxEnergy: 1000,
    energyRegen: 35,
    shieldRegen: 12,
    shieldRegenDelay: 4,
    maxSpeed: 8,
    acceleration: 3.5,
    turnSpeed: 4.5,
    deceleration: 5,
    arrivalRadius: 0.75,
    baseAltitude: 33,
    // Matches the scaled saucer mesh and its visible shield-impact shell.
    hullHitRadius: 11.95,
    hullHitHalfHeight: 2.5,
    shieldHitRadius: 12.15,
    shieldHitHalfHeight: 3.75,
  },
  beam: {
    range: 22,
    radius: 6.5,
    harvestPerSecond: 5000,
    biomassPerPerson: 100,
    tacticalEnergyPerThousand: 14,
    heatPerSecond: 14,
    heatWeightReference: 24,
    heatWeightMaxMultiplier: 1.65,
    heatAbsorptionRampUnits: 10000,
    heatAbsorptionMaxMultiplier: 1.6,
    heatRecoveryPerSecond: 50,
    heatWarningThreshold: 60,
    heatCriticalThreshold: 80,
    overheatRecoverySeconds: 2,
    impactHeatIncrease: 25,
    movementSpeedMultiplier: 0.5,
    rotationSpeedMultiplier: 0.7,
  },
  shieldCharge: {
    energyPerUse: 100,
    efficiency: 0.5,
  },
  objectives: { absorbTarget: 25000 },
  scan: { range: 28, autoRevealRange: 24, energy: 110, cooldown: 10 },
  cargo: { baseCapacity: 35000, capacityPerUpgrade: 10000 },
  plasma: {
    range: 28,
    radius: 4.5,
    energy: 90,
    cooldown: 3.5,
    facilityDamage: 220,
    collateralRatio: 0.12,
  },
  emp: { range: 28, radius: 18, energy: 180, cooldown: 16, duration: 8 },
  overdrive: { energy: 280, cooldown: 18, duration: 5, damageReduction: 0.6 },
  defense: {
    samHealth: 350,
    missileDamage: 90,
    missileSpeed: 16,
    missileInterval: 4.5,
    fighterHealth: 50,
    fighterDamage: 24,
    fighterInterval: 5.5,
    fighterAltitude: 24,
    fighterCruiseSpeed: 11.5,
    fighterMaxSpeed: 16,
    fighterAcceleration: 18,
    fighterOrbitRadius: 19,
    fighterOrbitAngularSpeed: 0.5,
    fighterAttackRunDepth: 5.5,
    fighterAttackRange: 28,
    fighterMinAttackRange: 9,
    fighterMinSquadSize: 4,
    fighterMaxCount: 20,
    fighterProjectileSpeed: 28,
    airDefenseLaser: { damage: 10, interval: 3 },
    samProjectileRadius: 0.25,
    fighterProjectileRadius: 0.14,
    pointDefenseRange: 14,
    pointDefenseInterval: 0.45,
    pointDefenseEnergy: 8,
  },
  alert: { basePerSecond: 0.25, beamPerSecond: 0.15 },
  extraction: { duration: 3, radius: 7 },
  travel: { minSeconds: 1.5, maxSeconds: 6 },
  conquest: {
    initialCoreCharge: 48,
    maxCoreCharge: 100,
    coreChargePerCell: 8,
    maxOverchargeCells: 3,
    emergencyTravelCharge: 8,
    emergencyChargePenaltyThreat: 2,
  },
  conversion: {
    captivesPerCohort: 5_000,
    captivesPerBiomass: 100,
    baseConversionCapacity: 2,
    baseCaptiveReserve: 50_000,
  },
  cohort: {
    baseStrength: 100,
    baseCohesion: 100,
    baseControl: 100,
    moveSpeed: 3.5,
    assaultRange: 2.5,
    assaultDamagePerSecond: 18,
    recoveryRadius: 8,
    baseCommandBandwidth: 2,
    baseDropCapacity: 2,
  },
  occupation: {
    requiredControlNodes: 2,
    captureSeconds: 8,
    requiredGarrisonCohorts: 1,
  },
} as const;
