const MOTHERSHIP_VISUAL_SCALE = 1.5;

export const BALANCE = {
  tacticalMap: {
    // The ground mesh spans -80..80. Keep the mothership inside this
    // smaller playable square so the outer six units can act as a visual
    // transition ring instead of exposing the floor's hard edge.
    groundHalfExtent: 80,
    playableHalfExtent: 74,
  },
  mothership: {
    visualScale: MOTHERSHIP_VISUAL_SCALE,
    maxHull: 1200,
    maxShield: 800,
    maxEnergy: 1000,
    energyRegen: 35,
    shieldRegen: 12,
    shieldRegenDelay: 4,
    maxSpeed: 8,
    acceleration: 3.5,
    turnSpeed: 4.5,
    deceleration: 5,
    arrivalRadius: 0.75,
    baseAltitude: 33,
    // Base hit volumes are scaled with the runtime saucer model.
    // Keep projectile contact close to the visible saucer body. These are
    // gameplay volumes, not the former oversized guidance bubble.
    hullHitRadius: 6.3 * MOTHERSHIP_VISUAL_SCALE,
    hullHitHalfHeight: 1.4 * MOTHERSHIP_VISUAL_SCALE,
    shieldHitRadius: 7.1 * MOTHERSHIP_VISUAL_SCALE,
    shieldHitHalfHeight: 1.9 * MOTHERSHIP_VISUAL_SCALE,
    shieldVisualRadius: 12.15 * MOTHERSHIP_VISUAL_SCALE,
    shieldVisualHalfHeight: 3.75 * MOTHERSHIP_VISUAL_SCALE,
  },
  beam: {
    range: 22,
    radius: 6.5,
    harvestPerSecond: 5000,
    durationMultiplier: 3,
    energyDrainPerSecond: 100,
    shelterBreachSeconds: 3,
    biomassPerPerson: 100,
    tacticalEnergyPerThousand: 14,
    heatPerSecond: 14,
    heatWeightReference: 24,
    heatWeightMaxMultiplier: 1.65,
    heatAbsorptionRampUnits: 10000,
    heatAbsorptionMaxMultiplier: 1.6,
    heatRecoveryPerSecond: 50,
    heatWarningThreshold: 60,
    heatCriticalThreshold: 80,
    overheatRecoverySeconds: 2,
    impactHeatIncrease: 25,
    movementSpeedMultiplier: 0.5,
    rotationSpeedMultiplier: 0.7,
  },
  shieldCharge: {
    energyPerUse: 100,
    efficiency: 0.5,
  },
  objectives: { absorbTarget: 25000 },
  scan: { range: 28, autoRevealRange: 24, energy: 110, cooldown: 10 },
  cargo: { baseCapacity: 35000, capacityPerUpgrade: 10000 },
  plasma: {
    range: 28,
    radius: 4.5,
    energy: 400,
    cooldown: 3.5,
    facilityDamage: 220,
    fighterDamage: 40,
    collateralRatio: 0.12,
  },
  emp: { range: 28, radius: 18, energy: 400, cooldown: 16, duration: 8 },
  overdrive: { energy: 400, cooldown: 18, duration: 5, damageReduction: 0.6 },
  defense: {
    samHealth: 350,
    missileDamage: 90,
    missileSpeed: 16,
    missileInterval: 4.5,
    fighterHealth: 50,
    fighterDamage: 24,
    fighterInterval: 5.5,
    fighterAltitude: 33,
    fighterCruiseSpeed: 15,
    fighterMaxSpeed: 24,
    fighterAcceleration: 20,
    fighterOrbitRadius: 40,
    fighterOrbitRadiusMin: 34,
    fighterOrbitRadiusMax: 46,
    fighterOrbitDepthRadiusMin: 34,
    fighterOrbitDepthRadiusMax: 42,
    fighterOrbitVerticalRadiusMin: 8,
    fighterOrbitVerticalRadiusMax: 14,
    fighterOrbitPlaneTiltMin: Math.PI * 8 / 180,
    fighterOrbitPlaneTiltMax: Math.PI * 20 / 180,
    fighterOrbitAngularSpeed: 0.29,
    fighterOrbitAngularSpeedMin: 0.2,
    fighterOrbitAngularSpeedMax: 0.38,
    fighterOrbitEccentricityMin: 0.06,
    fighterOrbitEccentricityMax: 0.14,
    fighterKeepOutRadiusX: 28,
    fighterKeepOutRadiusY: 9,
    fighterKeepOutRadiusZ: 28,
    fighterAttackPassRadiusMin: 30,
    fighterAttackPassDepth: 6,
    fighterAttackPassDuration: 2.4,
    fighterAttackPassSpeedMultiplier: 1.18,
    fighterRecoverDurationMin: 1.2,
    fighterRecoverDurationMax: 2,
    fighterAttackCycleSeconds: 13,
    fighterAttackRange: 52,
    fighterMinAttackRange: 30,
    fighterMinSquadSize: 4,
    fighterMaxCount: 20,
    fighterProjectileSpeed: 28,
    airDefenseLaser: { damage: 10, interval: 3 },
    samProjectileRadius: 0.25,
    fighterProjectileRadius: 0.14,
    pointDefenseRange: 14,
    pointDefenseInterval: 0.45,
    pointDefenseEnergy: 8,
    pointDefenseAccuracy: 0.75,
  },
  groundSwarm: {
    initialDelay: 2.5,
    interval: 8.4,
    projectilesPerBurst: 4,
    damagePerProjectile: 18,
    travelSpeed: 8.4,
    minimumDuration: 2,
    maximumDuration: 8,
    maximumActiveProjectiles: 20,
  },
  repair: {
    biomassAtTotalLoss: 180,
    alloyAtTotalLoss: 240,
    maximumWalletRatio: 0.45,
    emergencyHullRatio: 0.5,
  },
  abort: {
    cargoRecoveryRate: 0.35,
  },
  sideViewCohort: {
    deploymentDelay: 1.25,
    deploymentSpacing: 2.8,
  },
  alert: { basePerSecond: 0.25, beamPerSecond: 0.15 },
  extraction: { duration: 3, radius: 7 },
  travel: { minSeconds: 1.5, maxSeconds: 6 },
  conquest: {
    initialCoreCharge: 48,
    maxCoreCharge: 100,
    coreChargePerCell: 8,
    maxOverchargeCells: 3,
    emergencyTravelCharge: 8,
    emergencyChargePenaltyThreat: 2,
  },
  conversion: {
    captivesPerCohort: 5_000,
    captivesPerBiomass: 100,
    baseConversionCapacity: 2,
    baseCaptiveReserve: 50_000,
  },
  cohort: {
    baseStrength: 100,
    baseCohesion: 100,
    baseControl: 100,
    moveSpeed: 3.5,
    assaultRange: 2.5,
    assaultDamagePerSecond: 18,
    recoveryRadius: 8,
    baseCommandBandwidth: 2,
    baseDropCapacity: 2,
  },
  occupation: {
    requiredControlNodes: 2,
    captureSeconds: 8,
    requiredGarrisonCohorts: 1,
  },
} as const;
